const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //admin
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",

  //admin
  FECTH_GENDER_START: "FECTH_GENDER_START",
  FECTH_GENDER_SUCCESS: "FECTH_GENDER_SUCCESS",
  FECTH_GENDER_FAILED: "FECTH_GENDER_FAILED",

  FECTH_POSITION_START: "FECTH_POSITION_START",
  FECTH_POSITION_SUCCESS: "FECTH_POSITION_SUCCESS",
  FECTH_POSITION_FAILED: "FECTH_POSITION_FAILED",

  FECTH_ROLE_START: "FECTH_ROLE_START",
  FECTH_ROLE_SUCCESS: "FECTH_ROLE_SUCCESS",
  FECTH_ROLE_FAILED: "FECTH_ROLE_FAILED",

  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_FAILED: "SAVE_USER_FAILED",

  ALL_USERS_SUCCESS: "ALL_USERS_SUCCESS",
  ALL_USERS_FAILED: "ALL_USERS_FAILED",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILED: "UPDATE_USER_FAILED",

  FECTH_HOME_DOCTOR_SUCCESS: "FECTH_HOME_DOCTOR_SUCCESS",
  FECTH_HOME_DOCTOR_FAILED: "FECTH_HOME_DOCTOR_FAILED",

  FECTH_ALL_DOCTOR_SUCCESS: "FECTH_ALL_DOCTOR_SUCCESS",
  FECTH_ALL_DOCTOR_FAILED: "FECTH_ALL_DOCTOR_FAILED",

  FECTH_SAVE_INFO_DOCTOR_SUCCESS: "FECTH_SAVE_INFO_DOCTOR_SUCCESS",
  FECTH_SAVE_INFO_DOCTOR_FAILED: "FECTH_SAVE_INFO_DOCTOR_FAILED",

  FECTH_ALLCODE_DOCTOR_HOURS_SUCCESS: "FECTH_ALLCODE_DOCTOR_HOURS_SUCCESS",
  FECTH_ALLCODE_DOCTOR_HOURS_FAILED: "FECTH_ALLCODE_DOCTOR_HOURS_FAILED",
});

export default actionTypes;
